### ISSUE TITLE
Error: Sequence contains no elements

### ISSUE THREAD

**Issue by warpech** [Starcounter/Website#257] opened 2017-10-26 19:06 UTC
### Steps to reproduce

1. Clone Website `develop` branch (55c168f2b410c3524c1ec31511826b8505918007)
2. Have some specific data in the database ([SQLite dump](https://drive.google.com/file/d/0BzF8KHDi0CnNSGQzaHFmRWNlSWM/view?usp=sharing))
3. Build and run WebsiteEditor and WebsiteProvider using the batch files

### Expected result

The apps should start 

### Actual result

There is a startup exception when starting WebsiteProvider

```cs
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at WebsiteProvider.Api.BlendingHandlers.MapBlendingRule(WebMap webMap, Boolean tryDeactivate) in c:\www\StarcounterApps\Website\src\WebsiteProvider\Api\BlendingHandlers.cs:line 267
   at WebsiteProvider.Api.BlendingHandlers.Register() in c:\www\StarcounterApps\Website\src\WebsiteProvider\Api\BlendingHandlers.cs:line 52
   at WebsiteProvider.Program.Main() in c:\www\StarcounterApps\Website\src\WebsiteProvider\Program.cs:line 13
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-9837\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 529
Version: 2.3.1.7534.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-9837\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 563
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-9837\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-9837\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-9837\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-9837\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 89
ErrorCode=4259
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR4259
---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at WebsiteProvider.Api.BlendingHandlers.MapBlendingRule(WebMap webMap, Boolean tryDeactivate) in c:\www\StarcounterApps\Website\src\WebsiteProvider\Api\BlendingHandlers.cs:line 267
   at WebsiteProvider.Api.BlendingHandlers.Register() in c:\www\StarcounterApps\Website\src\WebsiteProvider\Api\BlendingHandlers.cs:line 52
   at WebsiteProvider.Program.Main() in c:\www\StarcounterApps\Website\src\WebsiteProvider\Program.cs:line 13
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-9837\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 529
HResult=-2146233079
```

### Screenshot

![image](https://user-images.githubusercontent.com/566463/32071847-e785c9a8-ba90-11e7-998d-0778fe72af83.png)

**Comment by un-tone** [comment] 2017-10-27 12:01
When I run the `reload` command
```
C:\Program Files\Starcounter\StarDump>StarDump.exe reload --database default --file C:\Users\untone\Documents\Temp\WebsiteEditor-issue-257.sqlite3
```
I'm getting the following error:
```
Starcounter.Core.StarcounterException: ScErrBadArguments (SCERR1001): One or more arguments was invalid. Property Deleted isn't found in class Simplified.Ring6.WebSection.
   at Starcounter.Core.Db.MetalayerCheck(UInt32 r)
   at StarDump.Core.CrudHelper..ctor(UInt64 dbHandle, ReloadTable table) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Helpers\CrudHelper.cs:line 47
   at StarDump.Core.Reload.<>c__DisplayClass28_0.<CreateTable>b__0() in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 242
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Reload.CreateTables(SqliteConnection cn, List`1 tables) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 209
   at StarDump.Core.Reload.CreateTablesAndInsertData(SqliteConnection cn, Int32& tablesCount, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 192
   at StarDump.Core.Reload.Run() in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\Reload.cs:line 78
   at StarDump.Core.CommandInterface.Reload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump.Core\CommandInterface.cs:line 46
   at StarDump.CommandLineInterface.<>c__DisplayClass10_1.<AddReloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-9934\StarDump\src\StarDump\CommandLineInterface.cs:line 292
```

Does it works well on your side, @warpech?

**Comment by warpech** [comment] 2017-10-27 12:23
I am getting the same error :( I made an issue in StarDump: https://github.com/Starcounter/StarDump/issues/69

**Comment by un-tone** [comment] 2017-11-17 09:06
After the fixes in StarDump I'm still getting the error `One or more arguments was invalid. Property Deleted isn't found in class Simplified.Ring6.WebSection.`. I suppose the attached dump file is invalid for current StarDump version.

**Comment by warpech** [comment] 2017-11-17 16:14
> After the fixes in StarDump I'm still getting the error `One or more arguments was invalid. Property Deleted isn't found in class Simplified.Ring6.WebSection.`. I suppose the attached dump file is invalid for current StarDump version.

@miyconst can this be true? In that case, let's close this issue.

**Comment by miyconst** [comment] 2017-11-17 17:13
>I suppose the attached dump file is invalid for current StarDump version.

It should not be so, unless I missed something. @un-tone are you sure you are using the updated StarDump? What version `StarDump.exe` shows?

**Comment by un-tone** [comment] 2017-11-20 11:19
```
C:\Program Files\Starcounter\StarDump>StarDump.exe --version

StarDump application version:    0.2.3
SQLite dump format version:      0.0.3
```

There are two cases. The one when `default` DB is clean and without running apps:

```
StarDump.exe reload --database default --file C:\Users\untone\Documents\Temp\WebsiteEditor-issue-257.sqlite3
...
Starcounter.Core.StarcounterException: ScErrBadArguments (SCERR1001): One or more arguments was invalid. Property Deleted isn't found in class Simplified.Ring6.WebSection.
   at Starcounter.Core.Db.MetalayerCheck(UInt32 r)
   at StarDump.Core.CrudHelper..ctor(UInt64 dbHandle, ReloadTable table) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Helpers\CrudHelper.cs:line 47
   at StarDump.Core.Reload.<>c__DisplayClass30_0.<CreateTable>b__0() in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 299
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Reload.CreateTables(SqliteConnection cn, List`1 tables) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 234
   at StarDump.Core.Reload.CreateTablesAndInsertData(Configuration config, SqliteConnection cn, Int32& tablesCount, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 199
   at StarDump.Core.Reload.Run() in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 78
   at StarDump.Core.CommandInterface.Reload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\CommandInterface.cs:line 46
   at StarDump.CommandLineInterface.<>c__DisplayClass10_1.<AddReloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump\CommandLineInterface.cs:line 298
```

The second when WebsiteEditor/WebsiteProviders are running:

```
StarDump.exe reload --forcereload --database default --file C:\Users\untone\Documents\Temp\WebsiteEditor-issue-257.sqlite3
...
Starcounter.Core.StarcounterException: SCERR15009 Schema of the input type does not match schema of existing type:
 Starcounter.HTMLComposition with input columns:
Version,Key
   at Starcounter.Core.Db.MetalayerCheck(UInt32 r)
   at StarDump.Core.Reload.CreateTable(ReloadTable table, List`1 columns) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 313
   at StarDump.Core.Reload.<>c__DisplayClass30_0.<CreateTable>b__0() in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 299
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Db.Transact(Action action, TransactOptions options)
   at StarDump.Core.Reload.CreateTables(SqliteConnection cn, List`1 tables) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 234
   at StarDump.Core.Reload.CreateTablesAndInsertData(Configuration config, SqliteConnection cn, Int32& tablesCount, UInt64& rowsCount) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 199
   at StarDump.Core.Reload.Run() in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\Reload.cs:line 78
   at StarDump.Core.CommandInterface.Reload(Configuration config, Output output) in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump.Core\CommandInterface.cs:line 46
   at StarDump.CommandLineInterface.<>c__DisplayClass10_1.<AddReloadCommand>b__1() in C:\TeamCity\BuildAgent\work\sc-11041\StarDump\src\StarDump\CommandLineInterface.cs:line 298
```

**Comment by miyconst** [comment] 2017-11-21 18:47
@un-tone please share the dump with me.

**Comment by un-tone** [comment] 2017-11-22 07:54
Sure, it is the same from the issue description: https://drive.google.com/file/d/0BzF8KHDi0CnNSGQzaHFmRWNlSWM/view?usp=sharing

**Comment by miyconst** [comment] 2017-11-22 09:54
@un-tone thank you for the dump. I am afraid this is expected behavior.

`StarDump.exe reload --database default --file WebsiteEditor-issue-257.sqlite3`

Since the  `--skipschema` is not provided, StarDump tries to create the database schema, and it's not possible since only a few tables are present in the dump. Such dump can only be reloaded with `--skipschema`.

>The second when WebsiteEditor/WebsiteProviders are running:

This is not allowed to reload a dump while there are some apps running. In this case not predicted behavior may happen. For the sake of speed, StarDump reload is executed in multiple transactions, means running apps may perform some actions between those transactions and interrupt the reloading process.

Also StarDump inserts objects with their `ObjectNo` values, the `--reassignobjectno` calculates the first available value and starts from there. In the end it means that if an app occupies an object number during reload, then there will be multiple objects with the same number and corrupted database.

Closing the issue. @warpech, @un-tone please reopen if something is not yet clear or the issue is persistent with newly created dumps.

**Closed by miyconst** 2017-11-22 09:54 UTC
Labels: WebsiteProvider
