### ISSUE TITLE
After deleting ResponsiveSurface or SidebarSurface redirecting doesn't work

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#200] opened 2017-09-15 10:29 UTC
### Steps to reproduce
1. Have WebsiteEditor, WebsiteProvider and SignIn running.
2. Login as an Admin user at http://localhost:8080/signin/signinuser
3. Go to http://localhost:8080/WebsiteEditor/resetdata
4. Go to http://localhost:8080/WebsiteEditor/surfacegroups
5. Go to ResponsiveSurface or SidebarSurface and remove it.
### Expected result
User is redirected to `/surfacegroups` page, as It's happening during deleting e.g HolyGrailSurface
### Actual result
Redirect doesn't work and user stays on empty page.

##### Starcounter version 2.3.1.7180

cc @un-tone 

BTW, 200th issue in website, Let's celebrate! 🎆 🎉

**Comment by un-tone** [comment] 2017-09-18 18:59
I think this issue is related to #186

**Comment by warpech** [comment] 2017-09-28 22:54
Bonus problem: After doing steps from the OT, do:

- Go to http://localhost:8080/WebsiteEditor/routing

## Expected

You should see a list of routes defined in WebsiteEditor

## Actual

You get `System.NullReferenceException: Object reference not set to an instance of an object`  and **the whole database crashes**. For me, the fact that WebsiteProvider can crash the entire database seems like a problem in Starcoutner 2.3 that @chrhol and @miyconst might want to take a look at.

Error log shows two errors:

```
System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.3.1.7294.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR1069.
   at StarcounterInternal.Hosting.Processor.<>c__DisplayClass3_0.<RunTaskNoScheduling>b__0() in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 138
   at Starcounter.Internal.StarcounterEnvironment.RunWithinApplicationInternal(String desiredAppName, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:line 142
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 121
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 168
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 81
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR1069
---> Starcounter.DbException: ScErrTransactionClosed (SCERR4260): An operation failed because transaction has been closed.
Version: 2.3.1.7294.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR4260.
   at Starcounter.Internal.TransactionManager.VerifyTransaction(TransactionHandle handle) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\TransactionManager.cs:line 348
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\TransactionManager.cs:line 548
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Transaction.cs:line 224
   at WebsiteEditor.Api.CommitHooks.<>c.<RefreshSignInState>b__1_0(Session session, String id) in c:\www\StarcounterApps\Website\src\WebsiteEditor\Api\CommitHooks.cs:line 38
   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 799
   at Starcounter.DbSession.<>c__DisplayClass5_0.<RunAsync>b__0() in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\DbSession.cs:line 216
   at Starcounter.Task.Run() in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\DbSession.cs:line 100
ErrorCode=4260
HResult=-2146233088
HelpLink=https://docs.starcounter.io/v/2.3.1/?q=SCERR4260
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Simplified.Ring1.Something.get_Name()
   at WebsiteEditor.ViewModels.RoutingPage.RefreshData() in c:\www\StarcounterApps\Website\src\WebsiteEditor\ViewModels\RoutingPage.json.cs:line 28
   at WebsiteEditor.ViewModels.MasterPage.RefreshCurrentPage() in c:\www\StarcounterApps\Website\src\WebsiteEditor\ViewModels\MasterPage.json.cs:line 34
   at WebsiteEditor.ViewModels.MasterPage.RefreshCurrentPage(String partialPageUrl) in c:\www\StarcounterApps\Website\src\WebsiteEditor\ViewModels\MasterPage.json.cs:line 16
   at WebsiteEditor.Api.Authorization.MasterPageMiddleware.Run(RoutingInfo routingInfo, Func`1 next) in c:\www\StarcounterApps\Website\src\WebsiteEditor\Api\Authorization\MasterPageMiddleware.cs:line 42
   at Starcounter.Authorization.Routing.Router.RunWithMiddleware(RoutingInfo routingInfo, IEnumerable`1 middlewares)
   at Starcounter.Authorization.Routing.Router.<>c__DisplayClass11_0.<RunWithMiddleware>b__0()
   at Starcounter.Authorization.Routing.Middleware.SecurityMiddleware.Run(RoutingInfo routingInfo, Func`1 next)
   at Starcounter.Authorization.Routing.Router.RunWithMiddleware(RoutingInfo routingInfo, IEnumerable`1 middlewares)
   at Starcounter.Authorization.Routing.Router.<>c__DisplayClass11_0.<RunWithMiddleware>b__0()
   at Starcounter.Db.<>c__DisplayClass50_0`1.<Scope>b__0() in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Db.cs:line 531
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Db.Scope(Action action, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Db.cs:line 505
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter\Db.cs:line 531
   at Starcounter.Authorization.Routing.Middleware.DbScopeMiddleware.Run(RoutingInfo routingInfo, Func`1 next)
   at Starcounter.Authorization.Routing.Router.RunWithMiddleware(RoutingInfo routingInfo, IEnumerable`1 middlewares)
   at Starcounter.Authorization.Routing.Router.RunResponse(Type pageType, Request request, String[] arguments)
   at Starcounter.Authorization.Routing.Router.<>c__DisplayClass8_0.<HandleGet>b__0(Request request)
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 231
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-8734\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
HResult=-2147467261
```

This is using:

- Starcounter 2.3.1.7294
- SignIn https://github.com/StarcounterApps/SignIn/tree/45ed21866d270f96ea605eb9086f6cf4de7e290a
- WebsiteEditor and WebsiteProvider https://github.com/StarcounterApps/Website/tree/bd591ed916dc4f3948628cb7ef9901344d2cda69

**Comment by miyconst** [comment] 2017-09-29 04:57
@chrhol please take a look, for me it sounds like Typed JSON tries to do something wrong with a closed transaction.

Even if the Website app is the culprit, it still should not crash entire database.

**Comment by un-tone** [comment] 2017-10-03 08:48
Created the PR #229 fixes the https://github.com/StarcounterApps/Website/issues/200#issuecomment-332985614 issue

**Comment by chrhol** [comment] 2017-10-03 08:58
Is this still something I should look at? That the whole codehost crashes is not really connected to this problem, this is the default behaviour for all exceptions thrown and not catched when a task is scheduled.

So what I could look at (unless @un-tone already found it of course) is why some viewmodel instance has a reference to a closed transaction.

**Comment by un-tone** [comment] 2017-10-03 09:08
Yes, it would be helpful. I haven't found it.

**Comment by un-tone** [comment] 2017-10-03 16:26
The JSON Patch after deleting seems to be correct:
![image](https://user-images.githubusercontent.com/1625378/31136252-538b5b8c-a870-11e7-9ca9-9e541b3b303f.png)
The issue seems similar to https://github.com/Starcounter/Home/issues/250

**Comment by warpech** [comment] 2017-10-03 22:04
@chrhol so is this really by design?

```cs
using System;
using Starcounter;
using System.Diagnostics;
using System.Collections.Generic;

namespace MyTest
{
    class Program
    {
        static void Main()
        {
            Handle.GET("/thiswillcrash", () => {
                Session.ForAll((Session session, string sessionId) => {
                    throw new Exception("This crashes all apps in the db");
                });
                return "ok";
            });
            //visit localhost:8080/thiswillcrash in your browser
        }
    }
}
```

**Comment by chrhol** [comment] 2017-10-04 07:26
> @chrhol so is this really by design?

Well "by design" might be a too strong word for it, but essentially yes. When an exception occurs that is not handled, we terminate the codehost (note: codehost, not database!) to make sure we don't end up in a corrupt/invalid state. 

We have had loong discussions on how we can improve this (for example: https://github.com/Starcounter/home/issues/51) but it requires quite some investigation and redesign.

`Session.ForAll` schedules a task for each existing session, so if a task throws an exception and you do not catch yourself, it will be treated as an unhandled exception.

**Comment by warpech** [comment] 2017-10-04 08:56
Another issue when an exception in data binding causes all apps to crash: https://github.com/StarcounterApps/Timeline/issues/37#issue-261785479

> `Session.ForAll` schedules a task for each existing session, so if a task throws an exception and you do not catch it yourself, it will be treated as an unhandled exception.

On the other hand, all exceptions in `Handle.GET` handlers are treated as handled exceptions and do not crash the codehost. Isn't this inconsistent? Maybe we should have a high level `Session.Push` method that works as

```cs
Session.Push(callb) {
  Session.ForAll((s) => {
    try { 
      callb(s); 
      s.CalculatePatchesAndSendOnWebSocket();
     } 
    catch (e) {
      DestroySession(s);
      LogError(e);
    }
  });
}
```

Right now the only solution I can think of is that all apps must include a `try/catch` in any async code. They don't do it at this point. This must be changed ASAP in the code and in the docs.

**Comment by chrhol** [comment] 2017-10-04 09:02
Yeah, there is plenty of room for improvements around this. We need to come up with some good way. I think we need to move this discussion to it's own issue though.

**Comment by chrhol** [comment] 2017-10-05 10:38
I think I found the reason for the closed transactions. Viewmodels stored on the session that are not part of what is sent to the client, doesn't correctly keep the attached transactions alive. 

Lets see if fixing this will have anything to do with the original issue (i.e. no redirect).

**Comment by chrhol** [comment] 2017-10-10 12:25
A fix for the closed transactions are now pushed and will be included in the next nightly builds. 

As for the original problem, this doesn't look like it changed anything. The redirect is still not redirecting. Not sure who should be assigned to this issue, but as @un-tone mentioned earlier, this issue looks similar to https://github.com/Starcounter/Home/issues/250 (and with that: https://github.com/Palindrom/palindrom-polymer-client/issues/47)

**Comment by chrhol** [comment] 2017-10-16 09:29
I will remove my assignment from this issue, I don't think I have anymore to do with with one at the moment.

**Comment by warpech** [comment] 2017-10-16 21:11
Let's wrap up:

1. Exceptions in asynchronous code crash the codehost. If we cannot fix this, we should explain this. I have created an issue about that: https://github.com/Starcounter/Docs/issues/166
2. After performing the steps 1-4 from OT and deleting "ResponsiveSurface" the user is not redirected to the Surface Groups page, but going to http://localhost:8080/WebsiteEditor/routing works OK
3. After performing the steps 1-4 from OT and deleting "SidebarSurface" the user is not redirected to the Surface Groups page, moreover going to http://localhost:8080/WebsiteEditor/routing shows an empty page

@chrhol thanks for investigating this so far.

Versions used to verify the above:

Starcounter 2.3.1.7454
https://github.com/Starcounter/Website/tree/c440fbfa65e9449fde5c890c1543b76b4162e0d8
https://github.com/StarcounterApps/SignIn/tree/e2b15fd35866a81006d47f1bae2ebbe02a5a6c4d

@PatrykSzwer do you see a way to investigate this further?

**Comment by PatrykSzwer** [comment] 2017-10-17 13:03
In my case both points 2 and 3 have same result (described at point 2). I can't reproduce getting empty page from point 3.

**Comment by PatrykSzwer** [comment] 2017-10-17 13:05
Also something happened to ResponsiveSurface and SidebarSurface, because they're not showing content anymore, either on side and in preview.

**Comment by un-tone** [comment] 2017-10-17 13:19
> I can't reproduce getting empty page from point 3.

Same thing

**Comment by warpech** [comment] 2017-10-17 14:15
Hmm... neither can now! Let's assume only point 2 is a problem then.

**Comment by warpech** [comment] 2017-11-03 09:13
@PatrykSzwer, @un-tone can you pls repeat the investigation? Where should the problem be fixed, in Starcounter, WebsiteEditor or WebsiteProvider?

**Comment by un-tone** [comment] 2017-11-03 11:26
The issue appears because after deleting the surface, the `document` does not contain the `palindrom-redirect`: https://github.com/Palindrom/palindrom-redirect/blob/e846d04e5ab48de9d3db3d7ef778b2d47e6979d3/palindrom-redirect.html#L29
I'm still not sure why.

Another note, when deleting not nested surface the view is not cleared and contains the `palindrom-redirect`:
![image](https://user-images.githubusercontent.com/1625378/32371658-c7545768-c0a2-11e7-8d1b-a750cb38c0b6.png)

When deleting nested surface the view is cleared and does not contain the `palindrom-redirect`:
![image](https://user-images.githubusercontent.com/1625378/32371695-ebd48e82-c0a2-11e7-9339-5f829cb4ab9e.png)

**Comment by un-tone** [comment] 2017-11-03 11:43
The issue seems to me like not a bug since we trying to use already deleted data.
I can propose the following solutions:

1. Use `Deleted` property for surfaces instead of permanent deleting.
2. Move `Delete` button to another page.

I'd prefer the first solution because the second one can have the same problem if the page will be included into deleting surface.

Note: I guess the issue with `Delete all surfaces` button from this PR https://github.com/Starcounter/Website/pull/262 looks the same.

**Comment by warpech** [comment] 2017-11-03 23:06
I vote for 1, but even better I would like the following:

1. user clicks the "Delete" button, which deletes the surface
2. this triggers a delete commit hook in WebsiteProvider
2. WebsiteProvider unmaps the surfaces before deleting
3. WebsiteProvider repeats the function https://github.com/Starcounter/Website/blob/a69aa8b94c11bb94806416b224a2b40974e87343/src/WebsiteProvider/Api/ContentHandlers.cs#L79 for all current sessions. This should remove the surface from being used because it is unmapped now
4. now the surface can be safely deleted

Of course 3 is hard, but maybe you know the way.

**Comment by PatrykSzwer** [comment] 2017-11-06 10:56
I'm also looking for first solution, rather than second. Specially since 2nd won't fix problem that occur in #262

**Comment by un-tone** [comment] 2017-11-07 13:00
I created PR https://github.com/Starcounter/Website/pull/266 for the 2nd solution. For the 3rd one described in https://github.com/Starcounter/Website/issues/200#issuecomment-341848568 I'll create a separate issue.

**Comment by PatrykSzwer** [comment] 2017-11-07 15:06
I would say that your PR is more about 1st solution:
> Use Deleted property for surfaces instead of permanent deleting.

 than 2nd, or Am I don't understanding something here?

**Comment by un-tone** [comment] 2017-11-07 15:07
Sure, fixed it :-)

**Comment by un-tone** [comment] 2017-11-09 14:23
Closing as done.

**Closed by un-tone** 2017-11-09 14:23 UTC
Labels: bug, desired, web

**Comment by warpech** [comment] 2018-01-10 17:21
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Website/releases/tag/4.0.0
