### ISSUE TITLE
Exception when clicking general tab two times

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Website#273] opened 2017-11-15 13:27 UTC
### Steps to reproduce
1. Go to http://localhost:8080/WebsiteEditor/surfacegroups and choose responsive or sidebar surface.
2. You will be at surface's general tab.
3. Click "General" on navigiation bar again.
### Expected result
Nothing happen.
### Actual result
You will get an error:
![image](https://user-images.githubusercontent.com/25042256/32838394-0c540d64-ca11-11e7-9870-d661f01cedbf.png)

##### Starcounter version 2.3.1.7772

**Comment by un-tone** [comment] 2017-11-15 14:10
I can't reproduce it in SC 2.3.1.7771

**Comment by un-tone** [comment] 2017-11-15 14:35
Did it. It is reproducible on nested pages.

**Comment by PatrykSzwer** [comment] 2017-11-15 14:36
I just wanted to write that, that reproduction can be done on responsive surface and sidebar surface.

**Comment by Mihaiii** [comment] 2017-11-15 23:58
Can't reproduce with SC 2.3.1.7779

**Comment by un-tone** [comment] 2017-11-16 09:20
It's still reproducible in SC 2.3.1.7786

**Comment by Mihaiii** [comment] 2017-11-16 09:33
I still can't reproduce it with that SC version so I suppose I'm doing something wrong.
Sorry for misinforming :).

**Comment by warpech** [comment] 2017-11-16 10:23
I have removed the label "P/Low" because we should only use the project board. In fact, I think this is of high priority because nested surfaces are a common scenario.

**Comment by un-tone** [comment] 2017-11-16 14:36
Created PR #276

**Comment by un-tone** [comment] 2017-11-16 17:05
Closing as done

**Closed by un-tone** 2017-11-16 17:05 UTC
Labels: bug
