### ISSUE TITLE
I had to manually stop the build with 79h overtime

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Website#261] opened 2017-10-30 15:08 UTC
http://teamcity.starcounter.org/viewLog.html?buildId=35462&tab=buildResultsDiv&buildTypeId=Apps_Website_Develop

**Comment by warpech** [comment] 2017-10-30 20:52
That's a hard working build, thanks for reporting!

Closing as duplicate of https://github.com/Starcounter/AdminTrack/issues/363

**Closed by warpech** 2017-10-30 20:52 UTC
